repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: latest
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-xml
    -   id: check-toml
    -   id: detect-private-key
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: check-added-large-files
    -   id: check-symlinks
    -   id: check-merge-conflict
    -   id: fix-byte-order-marker
